---
- name: Install dependencies
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - epel-release
    - git
    - wget
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - python3  # Install Python 3
    - python3-pip  # Install pip for Python 3

- name: Add Docker repository
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes

- name: Install Docker
  yum:
    name: docker-ce
    state: present
