---
- name: Install Docker prerequisites
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: >
      deb [arch=amd64]
      https://download.docker.com/linux/{{ ansible_distribution|lower }}
      {{ docker_distribution if docker_distribution is defined else ansible_distribution_release }}
      stable
    state: present

- name: Install Docker without containerd
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - docker-compose-plugin

- name: start docker service
  service:
    name: docker
    state: started


